# возвращает список категорий
GET http://localhost:3000/api/categories HTTP/1.1

###

# возвращает список публикаций
GET http://localhost:3000/api/articles HTTP/1.1

###

# возвращает полную информацию о публикации :articleId
# неверный id вызывает 404

GET http://localhost:3000/api/articles/bZAevi HTTP/1.1

###

# создаёт новую публикацию
# отсутствие необходимых ключей вызывает 400

POST http://localhost:3000/api/articles HTTP/1.1
Content-Type: application/json

{
  "title": "Большие деньги в мире фронтенда",
  "announce": "Достичь успеха помогут ежедневные повторения. Смеркалось. Ещё никогда Штирлиц не был так близок к провалу. Альбом стал настоящим открытием года. Мощные гитарные рифы и скоростные соло-партии не дадут заскучать.",
  "fullText": "Дуракам закон не писан. Вы можете достичь всего. Стоит только немного постараться и запастись книгами. Собрать камни бесконечности легко, если вы прирожденный герой. Альбом стал настоящим открытием года. Мощные гитарные рифы и скоростные соло-партии не дадут заскучать. Игры и программирование разные вещи. Не стоит идти в программисты, если вам нравится только игры. Бороться с прокрастинацией несложно. Просто действуйте. Маленькими шагами. Из под его пера вышло 8 платиновых альбомов. Программировать не настолько сложно, как об этом говорят.",
  "createdDate": "2020-08-07 15:27:15",
  "category": "За жизнь\nДеньги\nIT\nМузыка\nРазное\nДеревья\nКино\nФронтенд\nБез рамки\nКоты"
}

###

# редактирует определённую публикацию
# неверный id вызывает 404
# отсутствие необходимых ключей вызывает 400

PUT http://localhost:3000/api/articles/PXhavG HTTP/1.1
Content-Type: application/json

{
  "title": "Ёлки. История деревьев",
  "announce": "Дуракам закон не писан. Первая большая ёлка была установлена только в 1938 году. Помните, небольшое количество ежедневных упражнений лучше, чем один раз, но много. Не сделано — и переделывать не придется.",
  "fullText": "Альбом стал настоящим открытием года. Мощные гитарные рифы и скоростные соло-партии не дадут заскучать. Бороться с прокрастинацией несложно. Просто действуйте. Маленькими шагами.",
  "createdDate": "2020-10-19 15:27:15",
  "category": "Россия\nДеревья\nКино\nДети\nБез рамки\nЖелезо\nКоты\nОтношения\nМузыка\nЗа жизнь\nСоцсети"
}

###

# удаляет определённую публикацию
# повторное выполнение этого и других запросов с данным id возвращает 404

DELETE http://localhost:3000/api/articles/bZAevi HTTP/1.1

###

# возвращает список комментариев определённой публикации
# если публикация не существует, возвращает 404

GET http://localhost:3000/api/articles/7MJmkq/comments HTTP/1.1

###

# удаляет из определённой публикации комментарий с идентификатором
# если публикация или комментарий не существуют, возвращает 404 с содержательным ответом

DELETE http://localhost:3000/api/articles/7MJmkq/comments/rWOhuP HTTP/1.1

###

# создаёт новый комментарий
# неверный :articleId вызывает 404 с содержательным ответом
# отсутствие необходимых ключей вызывает 400

POST http://localhost:3000/api/articles/7MJmkq/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Это где ж такие красоты? Плюсую, но слишком много буквы! Планируете записать видосик на эту тему? Мне не нравится ваш стиль. Ощущение, что вы меня поучаете. Согласен с автором! Давно не пользуюсь стационарными компьютерами. Ноутбуки победили. Совсем немного..."
}

###

# возвращает результаты поиска
# поиск выполняется по заголовку
# публикация соответствует поиску в случае наличия хотя бы одного вхождения искомой фразы

GET http://localhost:3000/api/search?query=жить HTTP/1.1
